### ISSUE TITLE
Please distribute as npm package

### ISSUE THREAD

**Issue by TheDiveO** [amoldavsky/angular-mocks-async#22]
At this time, I get all the AngularJS and testing environment files as easily installable npm packages, but the only exception is angular-mocks-async. Would it be possible to distribute this library via the npm infrastructure?

**Comment by amoldavsky** [comment]
yes, this is in my TODO list, also to publish to yarn

**Comment by amoldavsky** [comment]
done https://www.npmjs.com/package/angular-mocks-async

just out of interest, how are you using it with NPM.
that setup did not work well for me in the past and I was wondering if I just missed something on the basic setup of things.

Would love to get your input

**Comment by TheDiveO** [comment]
I'm using it at the moment for automated testing of the services of an AngularJS app. The runner is Karma, with Chai for testing, et cetera. The runner as such is a GitLab CI job. For this reason it simplifies the setup or installation phase when I can simply run npm install for all required Angular JS and test dependencies. When Karma runs, I then pipe the dependencies through babel and browserify from their npm installed places into a single app run on a headless chrome browser.

**Comment by amoldavsky** [comment]
very interesting! thank you for sharing
