### ISSUE TITLE
Typo in source code

### ISSUE THREAD

**Issue by arcadeJHS** [amoldavsky/angular-mocks-async#6]
I guess there's a typo in angular-mocks-async.js, line 169, the "reponse" word.

Currently is:
`} else if( reponse.then && ( typeof reponse.then === 'function' ) ) {`

but should be:
`} else if( response.then && ( typeof response.then === 'function' ) ) {`

**Comment by amoldavsky** [comment]
thank you very much for pointing this out!

**Comment by amoldavsky** [comment]
fixed in [PR #8](https://github.com/amoldavsky/angular-mocks-async/pull/8)
